name: Caput
description: A Second Brain.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  confetti: ^0.7.0
  provider: ^6.0.5
  get_it: ^7.2.0
  uuid: ^3.0.6
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.13.0
  shared_preferences: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  drift: ^2.9.0
  get: ^4.6.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  path_provider: ^2.0.15
  faker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.9.0
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_caput.jpg"
  

flutter:
  uses-material-design: true
  assets:
      - assets/images/pb_dummy.jpeg
      - assets/images/static_noise.jpeg
      - assets/images/logo_caput_transparent.png
